<Project>
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Authors>Luiz Filho;Robert Asplund</Authors>
    <Copyright>Copyright © 2026 Luiz Filho</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Robert-LTH/PangYa-Suite-Tools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Robert-LTH/PangYa-Suite-Tools.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>pangya;game-files;modding;pak;iff</PackageTags>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild Condition="'$(CI)' != 'true'">true</GeneratePackageOnBuild>
    <PackageOutputPath>$(MSBuildThisFileDirectory)..\..\.nuget-local</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" Link="README.md" />
  </ItemGroup>
</Project>
